version: '3.9'

services:
    frontend:
        extends:
            file: docker-compose.yml
            service: frontend
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            NODE_ENV: production
            VITE_API_URL_BASE: http://localhost:8000
        command: npm run build
        volumes:
            - dist:/app/dist
            - /app/node_modules/
        ports:
            - 3000:3000
    volumes:
        dist:
