version: '3.9'

services:
    frontend:
        extends:
            file: ./docker-compose.base.yml
            service: frontend
        build:
            target: base
        environment:
            NODE_ENV: development
            VITE_API_URL_BASE: http://localhost:8000
            VITE_COMMIT_HASH: local
        command: npm run dev
        volumes:
            - .:/app
            - /app/node_modules/
        ports:
            - 3000:3000
