version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      VITE_API_URL_BASE: http://localhost:8000
    command: npm run dev
    volumes:
      - .:/app
    ports:
      - 3000:3000

volumes:
  node_modules:
