version: '3.9'

services:
  backend:
    extends:
      file: backend/docker-compose.yml
      service: backend
    depends_on:
      - db
  db:
    extends:
      file: backend/docker-compose.yml
      service: db
  frontend:
    extends:
      file: frontend/docker-compose.yml
      service: frontend

volumes:
  db-data:
  media_root:
