# Generated by Django 5.0 on 2023-12-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_itemtype_activity_notes_activity_rating_item_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
