# Generated by Django 5.0 on 2023-12-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_item_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"verbose_name_plural": "Activities"},
        ),
        migrations.AddField(
            model_name="itemtype",
            name="name_schema",
            field=models.TextField(blank=True),
        ),
    ]
