# Generated by Django 5.0 on 2023-12-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_activity_options_itemtype_name_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="settings",
            field=models.JSONField(default=dict),
        ),
    ]
