# Generated by Django 5.0 on 2024-01-07 20:23

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_item_parent_itemtype_parent_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemtype",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=app.models._item_type_icon_upload_helper,
            ),
        ),
    ]
