# Generated by Django 5.0 on 2024-01-29 01:14

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_item_pinned"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to=app.models._item_icon_upload_helper
            ),
        ),
    ]
