# Generated by Django 5.0 on 2024-02-14 03:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_item_icon"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itemtype",
            old_name="auto_complete_config",
            new_name="plugin_config",
        ),
    ]
